/* SPDX-License-Identifier: LGPL-3.0-only */

/* This is a **DUMMY** file to keep IDEs happy when editing
 * EmbeddedResources.hpp. The REAL file is automatically generated by the build
 * system from Config.in.h
 */
#ifndef EMBEDDED_RESOURCES_CONFIG_H
#define EMBEDDED_RESOURCES_CONFIG_H

/* The main namespace of the project the generated resources are embedded into.
 */
#define EMBEDDED_RESOURCES_PROJECT_NAMESPACE default_resource_compiler

#endif /* EMBEDDED_RESOURCES_CONFIG_H */
