/* SPDX-License-Identifier: LGPL-3.0-only */
#pragma once
#include "monomux/system/Platform.hpp"

#ifndef MONOMUX_CURRENT_PLATFORM_SUPPORTS_BACKTRACE
#define MONOMUX_CURRENT_PLATFORM_SUPPORTS_BACKTRACE
#endif /* MONOMUX_CURRENT_PLATFORM_SUPPORTS_BACKTRACE */
